package id.prasetya.vibrefy.tools;

import java.util.Iterator;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Short-lived pairing codes for moving a login onto a device that cannot practically
 * run the OAuth popup - a TV box, a handheld, a headset.
 *
 * Two directions share one table. In both of them the device that ends up signed in is
 * the one that writes its own session, so the session id can be rotated exactly as a
 * normal login does; nothing here ever reaches across into another request's session.
 *
 * Codes are eight digits rather than letters because they are read off a distant screen
 * and typed on a remote, a controller or a phone keypad. Digits also have no case and
 * no O/0 or I/1 ambiguity. The trade is a smaller space (10^8), so the attempt throttle
 * below is doing real work rather than being a formality.
 *
 * This is the RFC 8628 device-flow shape and carries its known weakness: a code can be
 * generated by an attacker and handed to a user to approve. The short life, the single
 * use, and showing the requesting browser and address on the approval screen reduce
 * that; they do not remove it.
 */
public class Pairing
{
  /** The device asked to be signed in and is waiting for someone to approve it. */
  public static final char KINDDEVICE='D';
  /** A signed-in user offered their identity for another device to claim. */
  public static final char KINDUSER='U';

  public static final int CODELENGTH=8;

  private static final long TTL=180000L;
  private static final long ATTEMPTWINDOW=300000L;
  private static final int MAXATTEMPTS=5;
  // Bounds the table against someone looping the request endpoint. Real use never has
  // more than a handful of codes alive at once.
  private static final int MAXPENDING=500;

  private static final ConcurrentHashMap<String,Entry> pending=new ConcurrentHashMap<>();
  private static final ConcurrentHashMap<String,long[]> failures=new ConcurrentHashMap<>();

  public static class Entry
  {
    private final String code;
    private final char kind;
    private final long created;
    private String sessionId=null;
    private String remoteAddr=null;
    private String userAgent=null;
    private boolean approved=false;
    private String email=null;
    private String accountId=null;
    private boolean admin=false;

    private Entry(String code,char kind)
    {
      this.code=code;
      this.kind=kind;
      this.created=System.currentTimeMillis();
    }

    public String getCode(){return code;}
    public char getKind(){return kind;}
    public String getSessionId(){return sessionId;}
    public String getRemoteAddr(){return remoteAddr==null?"":remoteAddr;}
    public String getUserAgent(){return userAgent==null?"":userAgent;}
    public boolean isApproved(){return approved;}
    public String getEmail(){return email;}
    public String getAccountId(){return accountId;}
    public boolean isAdmin(){return admin;}

    public boolean isExpired(){return System.currentTimeMillis()-created>TTL;}

    /** Seconds left before this code dies, for the countdown on screen. */
    public long getRemaining()
    {
      long left=(TTL-(System.currentTimeMillis()-created))/1000L;
      return left<0?0:left;
    }

    /** Carries the approver's identity into the record for the waiting device to pick up. */
    public void approve(String email,String accountId,boolean admin)
    {
      this.email=email;
      this.accountId=accountId;
      this.admin=admin;
      this.approved=true;
    }
  }

  /**
   * A device asking to be signed in. Bound to the session that asked, so learning the
   * code is not enough - the approval can only ever be collected by that same browser.
   */
  public static Entry createDevice(String sessionId,String remoteAddr,String userAgent)
  {
    Entry entry=create(KINDDEVICE);
    if (entry==null)return null;
    entry.sessionId=sessionId;
    entry.remoteAddr=remoteAddr;
    entry.userAgent=userAgent;
    return entry;
  }

  /**
   * A signed-in user offering their identity for another device to claim. This code is
   * a bearer credential while it lives, which is why it is only ever minted on an
   * explicit request and dies in three minutes.
   */
  public static Entry createUser(String email,String accountId,boolean admin)
  {
    Entry entry=create(KINDUSER);
    if (entry==null)return null;
    entry.email=email;
    entry.accountId=accountId;
    entry.admin=admin;
    entry.approved=true;
    return entry;
  }

  private static Entry create(char kind)
  {
    sweep();
    if (pending.size()>=MAXPENDING)return null;
    String code;
    do
    {
      code=Random.getNumeric(CODELENGTH);
    } while (pending.containsKey(code));
    Entry entry=new Entry(code,kind);
    pending.put(code,entry);
    return entry;
  }

  /** The live entry for a code, or null when it is unknown or has expired. */
  public static Entry get(String code)
  {
    sweep();
    if (code==null)return null;
    Entry entry=pending.get(normalise(code));
    if (entry==null)return null;
    if (entry.isExpired())
    {
      pending.remove(entry.code);
      return null;
    }
    return entry;
  }

  public static void remove(String code)
  {
    if (code!=null)pending.remove(normalise(code));
  }

  /**
   * Digits only, so a code pasted as "1234 5678" or typed with a stray dash still
   * matches what was generated.
   */
  public static String normalise(String code)
  {
    if (code==null)return "";
    StringBuilder rst=new StringBuilder();
    for (int i=0;i<code.length();i++)
    {
      char c=code.charAt(i);
      if (c>='0' && c<='9')rst.append(c);
    }
    return rst.toString();
  }

  /** Splits the code in half for display, which is markedly easier to read aloud. */
  public static String format(String code)
  {
    if (code==null || code.length()<CODELENGTH)return code==null?"":code;
    return code.substring(0,CODELENGTH/2)+" "+code.substring(CODELENGTH/2);
  }

  /**
   * Guessing throttle, keyed by source address rather than by session: a session
   * counter is defeated by simply dropping the cookie and asking again.
   */
  public static boolean tooManyAttempts(String remoteAddr)
  {
    if (remoteAddr==null)return false;
    long[] state=failures.get(remoteAddr);
    if (state==null)return false;
    if (System.currentTimeMillis()-state[1]>ATTEMPTWINDOW)
    {
      failures.remove(remoteAddr);
      return false;
    }
    return state[0]>=MAXATTEMPTS;
  }

  public static void noteFailure(String remoteAddr)
  {
    if (remoteAddr==null)return;
    long now=System.currentTimeMillis();
    failures.compute(remoteAddr,(key,state)->
    {
      if (state==null || now-state[1]>ATTEMPTWINDOW)return new long[]{1,now};
      state[0]++;
      return state;
    });
  }

  public static void clearFailures(String remoteAddr)
  {
    if (remoteAddr!=null)failures.remove(remoteAddr);
  }

  /**
   * Drops dead entries on the way past. No timer thread: the table is small enough that
   * walking it on each call costs nothing, and one less thread is one less thing to
   * unwind on redeploy.
   */
  private static void sweep()
  {
    long now=System.currentTimeMillis();
    for (Iterator<Map.Entry<String,Entry>> it=pending.entrySet().iterator();it.hasNext();)
    {
      if (now-it.next().getValue().created>TTL)it.remove();
    }
    for (Iterator<Map.Entry<String,long[]>> it=failures.entrySet().iterator();it.hasNext();)
    {
      if (now-it.next().getValue()[1]>ATTEMPTWINDOW)it.remove();
    }
  }
}
